### PR TITLE
Merge analysis.py updates to master

### PR DESCRIPTION
**Pull request by ltcptgeneral**
analysis.py v 1.2.1.004 and 1.2.2.000 added sort functions to analysis these were test during implementation and unit tests were added
changes were also made to test.py but the file was removed in tra-service and will be removed when that branch is merged

### CODE REVIEW

**Comment by devksingh4** [comment]
LGTM
Thanks for also writing the Unit tests for the sorts

**Comment by devksingh4** [comment]
@ltcptgeneral Can you have the tests also run on negative numbers? These sorts all look standard to me, but just want to make sure those are handled correctly

**Comment by jlevine18** [comment]
i'm not exactly sure why we need negatives in the unit tests (these are all generalized sorting algos that work on any two things that can be compared and i'm pretty sure that the python `int`/`float` comparison works as intended) but i guess it can't hurt. Maybe test with non-numerical comparables if you feel strongly about that then?

**Comment by ltcptgeneral** [comment]
> i'm not exactly sure why we need negatives in the unit tests (these are all generalized sorting algos that work on any two things that can be compared and i'm pretty sure that the python `int`/`float` comparison works as intended) but i guess it can't hurt. Maybe test with non-numerical comparables if you feel strongly about that then?
these weren't designed for non-numerical comparables yet, although one could serialize non-numericals to use the sorts.

**Comment by jlevine18** [comment]
> > i'm not exactly sure why we need negatives in the unit tests (these are all generalized sorting algos that work on any two things that can be compared and i'm pretty sure that the python `int`/`float` comparison works as intended) but i guess it can't hurt. Maybe test with non-numerical comparables if you feel strongly about that then?
> 
> these weren't designed for non-numerical comparables yet, although one could serialize non-numericals to use the sorts.

...but isn't `>` and `<` a general comparison operation? doesn't that mean that any valid (transitive) comparison works?

**Pull request merged**
